api = "0.5"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/python-start"
  id = "paketo-buildpacks/python-start"
  name = "Paketo Python Start Buildpack"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"
