api = "0.2"

[buildpack]
  id = "paketo-community/python-start"
  homepage = "https://github.com/paketo-community/python-start"
  name = "Paketo Python Start Buildpack"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[metadata]
  include-files = ["bin/run","bin/build","bin/detect","buildpack.toml"]
  pre-package = "./scripts/build.sh"
